---

- name: Create code_server_data_dir
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  with_items:
   - "{{ code_server.data_dir }}"
   - "{{ code_server.work_dir }}"
  become: true

- name: Install code server
  include_role:
    name: pallxk.code_server
  vars:
    code_server_password: "{{ code_server.password }}"
    code_server_user: "{{ code_server.user }}"
    code_server_host: "{{ code_server.host }}"
    code_server_port: "{{ code_server.port }}"
    code_server_data_dir: "{{ code_server.data_dir }}"
    code_server_work_dir: "{{ code_server.work_dir }}"
    code_server_env: "{{ code_server.env }}"

- name: Install pip
  apt:
    name: python3-pip
    update_cache: yes
  become: true

- name: Install ansible if required
  pip:
    name: ansible
    version: "{{ ansible_version }}"
  when: "'redhat.ansible' in code_server.extensions"

# - name: Install ipykernel if required
#   pip:
#     name: ipykernel
#   when: "'ms-toolsai.jupyter' in code_server.extensions"

- name: Install code server extensions
  shell:
    cmd: "code-server --install-extension {{ item }}"
  with_items: "{{ code_server.extensions }}"
  register: extension_installation
  changed_when: "'is already installed' not in extension_installation.stdout"