---

- name: Install Java 11
  apt:
    name: openjdk-11-jdk
    update_cache: true
  become: true
  become_user: root

- name: Install nextflow
  shell:
    cmd: "curl get.nextflow.io | bash"
    chdir: "{{ ansible_user_dir }}"
    creates: "{{ ansible_user_dir }}/nextflow"

- name: Copy nextflow binary to PATH
  copy:
    remote_src: true
    src: "{{ ansible_user_dir }}/nextflow"
    dest: "{{ nextflow_dir }}/nextflow"
    mode: 0744
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true

- name: Remove old nextflow binary
  file:
    path: "{{ ansible_user_dir }}/nextflow"
    state: absent  

# TODO: fix extension installation
# - name: Download code-server nextflow extension
#   shell:
#     cmd: "curl --output {{ nextflow_vsix_path }} {{ nextflow_vsix_url }}"
#     creates: "{{ nextflow_vsix_path }}"
#   when: install_code_server

# - name: Install code-server nextflow extension
#   command:
#     cmd: code-server --install-extension "{{ nextflow_vsix_path }}"
#   when: install_code_server
