---

- name: Install Java 11
  apt:
    name: openjdk-11-jdk
    update_cache: true
  become: true
  become_user: root

- name: Install nextflow
  shell:
    cmd: "curl get.nextflow.io | bash"
    chdir: "{{ ansible_user_dir }}"
    creates: "{{ ansible_user_dir }}/nextflow"

- name: Copy nextflow binary to PATH
  copy:
    remote_src: true
    src: "{{ ansible_user_dir }}/nextflow"
    dest: "{{ nextflow_dir }}/nextflow"
    mode: 0744
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true

- name: Remove old nextflow binary
  file:
    path: "{{ ansible_user_dir }}/nextflow"
    state: absent  

- name: Add nextflow language extension for code-server
  include_tasks: nextflow_extension.yml
  when: install_code_server
